class SechsNimmtCard(object):

    info = {'cards': [{'number': 1, 'penalty': 1}, {'number': 2, 'penalty': 1}, {'number': 3, 'penalty': 1}, {'number': 4, 'penalty': 1}, {'number': 5, 'penalty': 2}, {'number': 6, 'penalty': 1}, {'number': 7, 'penalty': 1}, {'number': 8, 'penalty': 1}, {'number': 9, 'penalty': 1}, {'number': 10, 'penalty': 3}, {'number': 11, 'penalty': 5}, {'number': 12, 'penalty': 1}, {'number': 13, 'penalty': 1}, {'number': 14, 'penalty': 1}, {'number': 15, 'penalty': 2}, {'number': 16, 'penalty': 1}, {'number': 17, 'penalty': 1}, {'number': 18, 'penalty': 1}, {'number': 19, 'penalty': 1}, {'number': 20, 'penalty': 3}, {'number': 21, 'penalty': 1}, {'number': 22, 'penalty': 5}, {'number': 23, 'penalty': 1}, {'number': 24, 'penalty': 1}, {'number': 25, 'penalty': 2}, {'number': 26, 'penalty': 1}, {'number': 27, 'penalty': 1}, {'number': 28, 'penalty': 1}, {'number': 29, 'penalty': 1}, {'number': 30, 'penalty': 3}, {'number': 31, 'penalty': 1}, {'number': 32, 'penalty': 1}, {'number': 33, 'penalty': 5}, {'number': 34, 'penalty': 1}, {'number': 35, 'penalty': 2}, {'number': 36, 'penalty': 1}, {'number': 37, 'penalty': 1}, {'number': 38, 'penalty': 1}, {'number': 39, 'penalty': 1}, {'number': 40, 'penalty': 3}, {'number': 41, 'penalty': 1}, {'number': 42, 'penalty': 1}, {'number': 43, 'penalty': 1}, {'number': 44, 'penalty': 5}, {'number': 45, 'penalty': 2}, {'number': 46, 'penalty': 1}, {'number': 47, 'penalty': 1}, {'number': 48, 'penalty': 1}, {'number': 49, 'penalty': 1}, {'number': 50, 'penalty': 3}, {'number': 51, 'penalty': 1}, {'number': 52, 'penalty': 1}, {
        'number': 53, 'penalty': 1}, {'number': 54, 'penalty': 1}, {'number': 55, 'penalty': 7}, {'number': 56, 'penalty': 1}, {'number': 57, 'penalty': 1}, {'number': 58, 'penalty': 1}, {'number': 59, 'penalty': 1}, {'number': 60, 'penalty': 3}, {'number': 61, 'penalty': 1}, {'number': 62, 'penalty': 1}, {'number': 63, 'penalty': 1}, {'number': 64, 'penalty': 1}, {'number': 65, 'penalty': 2}, {'number': 66, 'penalty': 5}, {'number': 67, 'penalty': 1}, {'number': 68, 'penalty': 1}, {'number': 69, 'penalty': 1}, {'number': 70, 'penalty': 3}, {'number': 71, 'penalty': 1}, {'number': 72, 'penalty': 1}, {'number': 73, 'penalty': 1}, {'number': 74, 'penalty': 1}, {'number': 75, 'penalty': 2}, {'number': 76, 'penalty': 1}, {'number': 77, 'penalty': 5}, {'number': 78, 'penalty': 1}, {'number': 79, 'penalty': 1}, {'number': 80, 'penalty': 3}, {'number': 81, 'penalty': 1}, {'number': 82, 'penalty': 1}, {'number': 83, 'penalty': 1}, {'number': 84, 'penalty': 1}, {'number': 85, 'penalty': 2}, {'number': 86, 'penalty': 1}, {'number': 87, 'penalty': 1}, {'number': 88, 'penalty': 5}, {'number': 89, 'penalty': 1}, {'number': 90, 'penalty': 3}, {'number': 91, 'penalty': 1}, {'number': 92, 'penalty': 1}, {'number': 93, 'penalty': 1}, {'number': 94, 'penalty': 1}, {'number': 95, 'penalty': 2}, {'number': 96, 'penalty': 1}, {'number': 97, 'penalty': 1}, {'number': 98, 'penalty': 1}, {'number': 99, 'penalty': 5}, {'number': 100, 'penalty': 3}, {'number': 101, 'penalty': 1}, {'number': 102, 'penalty': 1}, {'number': 103, 'penalty': 1}, {'number': 104, 'penalty': 1}]}

    def __init__(self, number, penalty):
        self.number = number
        self.penalty = penalty

    def __str__(self):
        return "%s (%s)"%(self.number, self.penalty)

    def get_str(self):
        return "%s-%s"%(self.number, self.penalty)